### ISSUE TITLE
Chemistry configuration Error

### ISSUE THREAD

**Issue by BishopFang** [SJMcMahonLab/ProtonTrackOverlapModel#1]
When I running the "ProtonTrackRadius_Chemistry.txt" file, an error occur:

TOPAS is exiting due to an error in Chemistry configuration.
--- Parameter: Ch/TOPASChemistry/BinaryReaction/Hydrogen/Hydrogen/ReactionRate
--- Molecule: ction was not found in database

How can I solve it?

**Comment by shannonthompson76** [comment]
Hi,
That looks like there may be a problem reading in the TOPASChemistry.txt file. Can I check you are reading that parameter file in okay? Another possible issue might be due to the TOPAS-nBio version, what version are you using?

**Comment by BishopFang** [comment]
Thanks for reply,
I changed my TOPASChemistry.txt to the following, then I made it worked:
`############################################################################################
# Diffusion coefficients
sv:Ch/TOPASChemistry/DiffusionCoefficients/Molecules = 7 "SolvatedElectron" "Hydroxyl"  "Hydrogen"  "Hydronium" "DyHydrogen" "Hydroxide" "HydrogenPeroxide"
dv:Ch/TOPASChemistry/DiffusionCoefficients/Values    = 7  4.90022052437e9 2.2e9 7e9 9.4601846875e9 4.8e9 5.3032890625e9 2.3e9 nm2/s

b:Ch/TOPASChemistry/SetWaterMolecularConfiguration = "False"

# Reaction rates
sv:Ch/TOPASChemistry/Reaction/SolvatedElectron/SolvatedElectron/Products    = 3 "Hydroxide" "Hydroxide" "Dyhydrogen"
d:Ch/TOPASChemistry/Reaction/SolvatedElectron/SolvatedElectron/ReactionRate = 0.647e10 /M/s
b:Ch/TOPASChemistry/Reaction/SolvatedElectron/SolvatedElectron/CompatibleWithStepByStep = "True"

sv:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydroxyl/Products            = 1 "Hydroxide"
d:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydroxyl/ReactionRate         = 2.953e10 /M/s
b:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydroxyl/CompatibleWithStepByStep = "True"

sv:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydrogen/Products            = 2 "Hydroxide" "Dyhydrogen"
d:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydrogen/ReactionRate         = 2.652e10 /M/s
b:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydrogen/CompatibleWithStepByStep = "True"

sv:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydronium/Products           = 1 "Hydrogen"
d:Ch/TOPASChemistry/Reaction/SolvatedElectron/Hydronium/ReactionRate        = 2.109e10 /M/s

sv:Ch/TOPASChemistry/Reaction/SolvatedElectron/HydrogenPeroxide/Products    = 2 "Hydroxide" "Hydroxyl"
d:Ch/TOPASChemistry/Reaction/SolvatedElectron/HydrogenPeroxide/ReactionRate = 1.405e10 /M/s

sv:Ch/TOPASChemistry/Reaction/Hydroxyl/Hydroxyl/Products                    = 1 "HydrogenPeroxide"
d:Ch/TOPASChemistry/Reaction/Hydroxyl/Hydroxyl/ReactionRate                 = 0.475e10 /M/s

sv:Ch/TOPASChemistry/Reaction/Hydroxyl/Hydrogen/Products                    = 1 "None"
d:Ch/TOPASChemistry/Reaction/Hydroxyl/Hydrogen/ReactionRate                 = 1.438e10 /M/s

sv:Ch/TOPASChemistry/Reaction/Hydrogen/Hydrogen/Products                    = 1 "Dyhydrogen"
d:Ch/TOPASChemistry/Reaction/Hydrogen/Hydrogen/ReactionRate                 = 0.503e10 /M/s

sv:Ch/TOPASChemistry/Reaction/Hydronium/Hydroxide/Products                  = 1 "None"
d:Ch/TOPASChemistry/Reaction/Hydronium/Hydroxide/ReactionRate               = 11.031e10 /M/s

###
###############################################################################################`
